blank_issues_enabled: true
contact_links:
  - name: General
    url: https://github.com/NOAA-EMC/WW3/discussions/categories/general
    about: Chat about anything and everything here
  - name: Announcements
    url: https://github.com/NOAA-EMC/WW3/discussions/categories/announcements
    about: Updates from maintainers
  - name: Ideas
    url: https://github.com/NOAA-EMC/WW3/discussions/categories/ideas
    about: Share ideas for new features
  - name: Q&A
    url: https://github.com/NOAA-EMC/WW3/discussions/categories/q-a
    about: Ask the community for help
  - name: Show and tell
    url: https://github.com/NOAA-EMC/WW3/discussions/categories/show-and-tell
    about: Show off something you've made
