#!/bin/sh
# --------------------------------------------------------------------------- #
# matrix : Brute force way of running a large set of regression tests.        #
#                                                                             #
#          This version is set up for a global .wwatch3.env file and for      #
#          the NOAA RDHPC 'zeus' system. When using this for your own         #
#          isetup and computer, please copy rather than modify.               #
#                                                                             #
#                                                      Hendrik L. Tolman      #
#                                                      July 2013              #
#                                                                             #
#    Copyright 2013 National Weather Service (NWS),                           #
#       National Oceanic and Atmospheric Administration.  All rights          #
#       reserved.  WAVEWATCH III is a trademark of the NWS.                   #
#       No unauthorized use without permission.                               #
#                                                                             #
# --------------------------------------------------------------------------- #

#PBS -l procs=12
#PBS -q batch
#PBS -l walltime=06:00:00
#PBS -A omd
#PBS -N ww3_regtest
#PBS -j oe
#PBS -o matrix.out

  cd /scratch1/portfolios/NCEPDEV/ocean/save/Hendrik.Tolman/wwatch3/regtests

  mpi='mpiexec_mpt'
   np='12'

 rtst="./bin/run_test -a $HOME/.wwatch3.env"
  ww3='../.'

#
# Hendrik's sanity :
#
#   # in 1st pos: switch off for this run
#   # in 2nd pos: does not work (yet)
#   # in 3nd pos: only used to test run_test in default mode

# --------------------------------------------------------------------------- #
# Pure propagation tests                                                      #
# --------------------------------------------------------------------------- #

    $rtst -s PR1         -w work_PR1                                    $ww3 ww3_tp1.1
    $rtst -s PR1         -w work_PR1                                    $ww3 ww3_tp1.2
    $rtst -s PR1         -w work_PR1                                    $ww3 ww3_tp1.3
    $rtst -s PR1         -w work_PR1                                    $ww3 ww3_tp1.4
    $rtst -s PR1         -w work_PR1                                    $ww3 ww3_tp1.5
    $rtst -s PR1         -w work_PR1                                    $ww3 ww3_tp1.6

    $rtst -s PR1         -w work_PR1                                    $ww3 ww3_tp2.1
    $rtst -s PR1         -w work_PR1                                    $ww3 ww3_tp2.2
    $rtst -s PR1         -w work_PR1                                    $ww3 ww3_tp2.3
    $rtst -s PR1         -w work_PR1                                    $ww3 ww3_tp2.4
    $rtst -s PR1         -w work_PR1_curv     -g curv                   $ww3 ww3_tp2.4
    $rtst -s PR1         -w work_PR1                                    $ww3 ww3_tp2.5

    $rtst -s PR1_MPI     -w work_PR1_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.1
    $rtst -s PR1_MPI     -w work_PR1_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.2
    $rtst -s PR1_MPI     -w work_PR1_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.3
    $rtst -s PR1_MPI     -w work_PR1_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.4
    $rtst -s PR1_MPI     -w work_PR1_curv_MPI -g curv -f -p $mpi -n $np $ww3 ww3_tp2.4
    $rtst -s PR1_MPI     -w work_PR1_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.5

    $rtst -s PR2         -w work_PR2                                    $ww3 ww3_tp1.1
    $rtst -s PR2         -w work_PR2                                    $ww3 ww3_tp1.2
    $rtst -s PR2         -w work_PR2                                    $ww3 ww3_tp1.3
    $rtst -s PR2         -w work_PR2                                    $ww3 ww3_tp1.4
    $rtst -s PR2         -w work_PR2                                    $ww3 ww3_tp1.5
    $rtst -s PR2         -w work_PR2                                    $ww3 ww3_tp1.6

    $rtst -s PR2         -w work_PR2                                    $ww3 ww3_tp2.1
    $rtst -s PR2         -w work_PR2                                    $ww3 ww3_tp2.2
    $rtst -s PR2         -w work_PR2                                    $ww3 ww3_tp2.3
    $rtst -s PR2         -w work_PR2                                    $ww3 ww3_tp2.4
    $rtst -s PR2         -w work_PR2_curv     -g curv                   $ww3 ww3_tp2.4
    $rtst -s PR2         -w work_PR2                                    $ww3 ww3_tp2.5

    $rtst -s PR2_MPI     -w work_PR2_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.1
    $rtst -s PR2_MPI     -w work_PR2_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.2
    $rtst -s PR2_MPI     -w work_PR2_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.3
    $rtst -s PR2_MPI     -w work_PR2_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.4
    $rtst -s PR2_MPI     -w work_PR2_curv_MPI -g curv -f -p $mpi -n $np $ww3 ww3_tp2.4
    $rtst -s PR2_MPI     -w work_PR2_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.5

    $rtst -s PR3         -w work_PR3                                    $ww3 ww3_tp1.1
    $rtst -s PR3         -w work_PR3                                    $ww3 ww3_tp1.2
    $rtst -s PR3         -w work_PR3                                    $ww3 ww3_tp1.3
    $rtst -s PR3         -w work_PR3                                    $ww3 ww3_tp1.4
    $rtst -s PR3         -w work_PR3                                    $ww3 ww3_tp1.5
    $rtst -s PR3         -w work_PR3                                    $ww3 ww3_tp1.6

    $rtst -s PR3         -w work_PR3                                    $ww3 ww3_tp2.1
    $rtst -s PR3         -w work_PR3                                    $ww3 ww3_tp2.2
    $rtst -s PR3         -w work_PR3                                    $ww3 ww3_tp2.3
    $rtst -s PR3         -w work_PR3                                    $ww3 ww3_tp2.4
    $rtst -s PR3         -w work_PR3_curv     -g curv                   $ww3 ww3_tp2.4
    $rtst -s PR3         -w work_PR3                                    $ww3 ww3_tp2.5

    $rtst -s PR3_MPI     -w work_PR3_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.1
    $rtst -s PR3_MPI     -w work_PR3_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.2
    $rtst -s PR3_MPI     -w work_PR3_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.3
    $rtst -s PR3_MPI     -w work_PR3_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.4
    $rtst -s PR3_MPI     -w work_PR3_curv_MPI -g curv -f -p $mpi -n $np $ww3 ww3_tp2.4
    $rtst -s PR3_MPI     -w work_PR3_MPI              -f -p $mpi -n $np $ww3 ww3_tp2.5

# -------------------------------------------------------------------------- #
# Source term tests                                                          #
# -------------------------------------------------------------------------- #

    $rtst -s ST1         -w work_ST1                           $ww3 ww3_ts1
    $rtst -s ST1_RWND    -w work_ST1_RWND                      $ww3 ww3_ts1
    $rtst -s ST2         -w work_ST2                           $ww3 ww3_ts1
    $rtst -s ST3         -w work_ST3                           $ww3 ww3_ts1
    $rtst -s ST4         -w work_ST4                           $ww3 ww3_ts1

    $rtst -s ST1_PR1     -w work_ST1_PR1                       $ww3 ww3_ts2
    $rtst -s ST1_PR2     -w work_ST1_PR2                       $ww3 ww3_ts2
    $rtst -s ST1_PR3     -w work_ST1_PR3                       $ww3 ww3_ts2
    $rtst -s ST2_PR1     -w work_ST2_PR1                       $ww3 ww3_ts2
    $rtst -s ST2_PR2     -w work_ST2_PR2                       $ww3 ww3_ts2
    $rtst -s ST2_PR3     -w work_ST2_PR3                       $ww3 ww3_ts2
    $rtst -s ST3_PR1     -w work_ST3_PR1                       $ww3 ww3_ts2
    $rtst -s ST3_PR2     -w work_ST3_PR2                       $ww3 ww3_ts2
    $rtst -s ST3_PR3     -w work_ST3_PR3                       $ww3 ww3_ts2
    $rtst -s ST4_PR1     -w work_ST4_PR1                       $ww3 ww3_ts2
    $rtst -s ST4_PR2     -w work_ST4_PR2                       $ww3 ww3_ts2
    $rtst -s ST4_PR3     -w work_ST4_PR3                       $ww3 ww3_ts2

    $rtst -s ST1_PR1     -w work_ST1_PR1                       $ww3 ww3_ts3
    $rtst -s ST1_PR2     -w work_ST1_PR2                       $ww3 ww3_ts3
    $rtst -s ST1_PR3     -w work_ST1_PR3                       $ww3 ww3_ts3
    $rtst -s ST2_PR1     -w work_ST2_PR1                       $ww3 ww3_ts3
    $rtst -s ST2_PR2     -w work_ST2_PR2                       $ww3 ww3_ts3
    $rtst -s ST2_PR3     -w work_ST2_PR3                       $ww3 ww3_ts3
    $rtst -s ST3_PR1     -w work_ST3_PR1                       $ww3 ww3_ts3
    $rtst -s ST3_PR2     -w work_ST3_PR2                       $ww3 ww3_ts3
    $rtst -s ST3_PR3     -w work_ST3_PR3                       $ww3 ww3_ts3
    $rtst -s ST4_PR1     -w work_ST4_PR1                       $ww3 ww3_ts3
    $rtst -s ST4_PR2     -w work_ST4_PR2                       $ww3 ww3_ts3
    $rtst -s ST4_PR3     -w work_ST4_PR3                       $ww3 ww3_ts3

    $rtst -s ST1_PR1_MPI -w work_ST1_PR1_MPI -f -p $mpi -n $np $ww3 ww3_ts3
    $rtst -s ST1_PR2_MPI -w work_ST1_PR2_MPI -f -p $mpi -n $np $ww3 ww3_ts3
    $rtst -s ST1_PR3_MPI -w work_ST1_PR3_MPI -f -p $mpi -n $np $ww3 ww3_ts3
    $rtst -s ST2_PR1_MPI -w work_ST2_PR1_MPI -f -p $mpi -n $np $ww3 ww3_ts3
    $rtst -s ST2_PR2_MPI -w work_ST2_PR2_MPI -f -p $mpi -n $np $ww3 ww3_ts3
    $rtst -s ST2_PR3_MPI -w work_ST2_PR3_MPI -f -p $mpi -n $np $ww3 ww3_ts3
    $rtst -s ST3_PR1_MPI -w work_ST3_PR1_MPI -f -p $mpi -n $np $ww3 ww3_ts3
    $rtst -s ST3_PR2_MPI -w work_ST3_PR2_MPI -f -p $mpi -n $np $ww3 ww3_ts3
    $rtst -s ST3_PR3_MPI -w work_ST3_PR3_MPI -f -p $mpi -n $np $ww3 ww3_ts3
    $rtst -s ST4_PR1_MPI -w work_ST4_PR1_MPI -f -p $mpi -n $np $ww3 ww3_ts3
    $rtst -s ST4_PR2_MPI -w work_ST4_PR2_MPI -f -p $mpi -n $np $ww3 ww3_ts3
    $rtst -s ST4_PR3_MPI -w work_ST4_PR3_MPI -f -p $mpi -n $np $ww3 ww3_ts3

# --------------------------------------------------------------------------- #
# Multigrid tests                                                             #
# --------------------------------------------------------------------------- #
# Note that test 04 has separate grid sets for MPI and non-MPI tests.

    $rtst -s PR1           -w work_PR1                                                 $ww3 mww3_test_01
    $rtst -s PR1           -w work_PR1_a        -m grdset_a                            $ww3 mww3_test_02
    $rtst -s PR1           -w work_PR1_b        -m grdset_b                            $ww3 mww3_test_02
    $rtst -s PR1           -w work_PR1_c        -m grdset_c                            $ww3 mww3_test_02
    $rtst -s PR1           -w work_PR1_d        -m grdset_d                            $ww3 mww3_test_02
    $rtst -s PR1           -w work_PR1_a        -m grdset_a                            $ww3 mww3_test_03
    $rtst -s PR1           -w work_PR1_b        -m grdset_b                            $ww3 mww3_test_03
    $rtst -s PR1           -w work_PR1_c        -m grdset_c                            $ww3 mww3_test_03
    $rtst -s PR1           -w work_PR1_d        -m grdset_d                            $ww3 mww3_test_03
    $rtst -s PR1           -w work_PR1_d2       -m grdset_d2                           $ww3 mww3_test_03
    $rtst -s PR1           -w work_PR1_e        -m grdset_e                            $ww3 mww3_test_03
    $rtst -s PR1           -w work_PR1_a        -m grdset_a                            $ww3 mww3_test_04
    $rtst -s PR1           -w work_PR1_b        -m grdset_b                            $ww3 mww3_test_04
    $rtst -s PR1           -w work_PR1_f        -m grdset_f                            $ww3 mww3_test_04
    $rtst -s PR1           -w work_PR1_g        -m grdset_g                            $ww3 mww3_test_04

    $rtst -s PR2           -w work_PR2                                                 $ww3 mww3_test_01
    $rtst -s PR2           -w work_PR2_a        -m grdset_a                            $ww3 mww3_test_02
    $rtst -s PR2           -w work_PR2_b        -m grdset_b                            $ww3 mww3_test_02
    $rtst -s PR2           -w work_PR2_c        -m grdset_c                            $ww3 mww3_test_02
    $rtst -s PR2           -w work_PR2_d        -m grdset_d                            $ww3 mww3_test_02
    $rtst -s PR2           -w work_PR2_a        -m grdset_a                            $ww3 mww3_test_03
    $rtst -s PR2           -w work_PR2_b        -m grdset_b                            $ww3 mww3_test_03
    $rtst -s PR2           -w work_PR2_c        -m grdset_c                            $ww3 mww3_test_03
    $rtst -s PR2           -w work_PR2_d        -m grdset_d                            $ww3 mww3_test_03
    $rtst -s PR2           -w work_PR2_d2       -m grdset_d2                           $ww3 mww3_test_03
    $rtst -s PR2           -w work_PR2_e        -m grdset_e                            $ww3 mww3_test_03
    $rtst -s PR2           -w work_PR2_a        -m grdset_a                            $ww3 mww3_test_04
    $rtst -s PR2           -w work_PR2_b        -m grdset_b                            $ww3 mww3_test_04
    $rtst -s PR2           -w work_PR2_f        -m grdset_f                            $ww3 mww3_test_04
    $rtst -s PR2           -w work_PR2_g        -m grdset_g                            $ww3 mww3_test_04

    $rtst -s PR3           -w work_PR3                                                 $ww3 mww3_test_01
    $rtst -s PR3           -w work_PR3_a        -m grdset_a                            $ww3 mww3_test_02
    $rtst -s PR3           -w work_PR3_b        -m grdset_b                            $ww3 mww3_test_02
    $rtst -s PR3           -w work_PR3_c        -m grdset_c                            $ww3 mww3_test_02
    $rtst -s PR3           -w work_PR3_d        -m grdset_d                            $ww3 mww3_test_02
    $rtst -s PR3           -w work_PR3_a        -m grdset_a                            $ww3 mww3_test_03
    $rtst -s PR3           -w work_PR3_b        -m grdset_b                            $ww3 mww3_test_03
    $rtst -s PR3           -w work_PR3_c        -m grdset_c                            $ww3 mww3_test_03
    $rtst -s PR3           -w work_PR3_d        -m grdset_d                            $ww3 mww3_test_03
    $rtst -s PR3           -w work_PR3_d2       -m grdset_d2                           $ww3 mww3_test_03
    $rtst -s PR3           -w work_PR3_e        -m grdset_e                            $ww3 mww3_test_03
    $rtst -s PR3           -w work_PR3_a        -m grdset_a                            $ww3 mww3_test_04
    $rtst -s PR3           -w work_PR3_b        -m grdset_b                            $ww3 mww3_test_04
    $rtst -s PR3           -w work_PR3_f        -m grdset_f                            $ww3 mww3_test_04
    $rtst -s PR3           -w work_PR3_g        -m grdset_g                            $ww3 mww3_test_04

    $rtst -s PR3_SCRIP     -w work_PR3_a_c      -m grdset_a  -g curv                   $ww3 mww3_test_02
    $rtst -s PR3_SCRIP     -w work_PR3_b_c      -m grdset_b  -g curv                   $ww3 mww3_test_02
    $rtst -s PR3_SCRIP     -w work_PR3_c_c      -m grdset_c  -g curv                   $ww3 mww3_test_02
    $rtst -s PR3_SCRIP     -w work_PR3_d_c      -m grdset_d  -g curv                   $ww3 mww3_test_02
    $rtst -s PR3_SCRIP     -w work_PR3_a_c      -m grdset_a                            $ww3 mww3_test_03
    $rtst -s PR3_SCRIP     -w work_PR3_b_c      -m grdset_b                            $ww3 mww3_test_03
    $rtst -s PR3_SCRIP     -w work_PR3_c_c      -m grdset_c                            $ww3 mww3_test_03
    $rtst -s PR3_SCRIP     -w work_PR3_d_c      -m grdset_d                            $ww3 mww3_test_03
    $rtst -s PR3_SCRIP     -w work_PR3_d2_c     -m grdset_d2                           $ww3 mww3_test_03
    $rtst -s PR3_SCRIP     -w work_PR3_e_c      -m grdset_e                            $ww3 mww3_test_03
    $rtst -s PR3_SCRIP     -w work_PR3_a_c      -m grdset_a                            $ww3 mww3_test_04
    $rtst -s PR3_SCRIP     -w work_PR3_b_c      -m grdset_b                            $ww3 mww3_test_04
    $rtst -s PR3_SCRIP     -w work_PR3_f_c      -m grdset_f                            $ww3 mww3_test_04
    $rtst -s PR3_SCRIP     -w work_PR3_g_c      -m grdset_g                            $ww3 mww3_test_04

    $rtst -s PR1_MPI       -w work_PR1_MPI                           -f -p $mpi -n $np $ww3 mww3_test_01
    $rtst -s PR1_MPI       -w work_PR1_MPI_a    -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR1_MPI       -w work_PR1_MPI_b    -m grdset_b          -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR1_MPI       -w work_PR1_MPI_c    -m grdset_c          -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR1_MPI       -w work_PR1_MPI_d    -m grdset_d          -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR1_MPI       -w work_PR1_MPI_a    -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR1_MPI       -w work_PR1_MPI_b    -m grdset_b          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR1_MPI       -w work_PR1_MPI_c    -m grdset_c          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR1_MPI       -w work_PR1_MPI_d    -m grdset_d          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR1_MPI       -w work_PR1_MPI_d2   -m grdset_d2         -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR1_MPI       -w work_PR1_MPI_e    -m grdset_e          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR1_MPI       -w work_PR1_MPI_b    -m grdset_b          -f -p $mpi -n $np $ww3 mww3_test_04
    $rtst -s PR1_MPI       -w work_PR1_MPI_c    -m grdset_c          -f -p $mpi -n $np $ww3 mww3_test_04
    $rtst -s PR1_MPI       -w work_PR1_MPI_d    -m grdset_d          -f -p $mpi -n $np $ww3 mww3_test_04
    $rtst -s PR1_MPI       -w work_PR1_MPI_e    -m grdset_e          -f -p $mpi -n $np $ww3 mww3_test_04

    $rtst -s PR2_MPI       -w work_PR2_MPI                           -f -p $mpi -n $np $ww3 mww3_test_01
    $rtst -s PR2_MPI       -w work_PR2_MPI_a    -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR2_MPI       -w work_PR2_MPI_b    -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR2_MPI       -w work_PR2_MPI_c    -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR2_MPI       -w work_PR2_MPI_d    -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR2_MPI       -w work_PR2_MPI_a    -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR2_MPI       -w work_PR2_MPI_b    -m grdset_b          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR2_MPI       -w work_PR2_MPI_c    -m grdset_c          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR2_MPI       -w work_PR2_MPI_d    -m grdset_d          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR2_MPI       -w work_PR2_MPI_d2   -m grdset_d2         -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR2_MPI       -w work_PR2_MPI_e    -m grdset_e          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR2_MPI       -w work_PR2_MPI_b    -m grdset_b          -f -p $mpi -n $np $ww3 mww3_test_04
    $rtst -s PR2_MPI       -w work_PR2_MPI_c    -m grdset_c          -f -p $mpi -n $np $ww3 mww3_test_04
    $rtst -s PR2_MPI       -w work_PR2_MPI_d    -m grdset_d          -f -p $mpi -n $np $ww3 mww3_test_04
    $rtst -s PR2_MPI       -w work_PR2_MPI_e    -m grdset_e          -f -p $mpi -n $np $ww3 mww3_test_04

    $rtst -s PR3_MPI       -w work_PR3_MPI                           -f -p $mpi -n $np $ww3 mww3_test_01
    $rtst -s PR3_MPI       -w work_PR3_MPI_a    -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR3_MPI       -w work_PR3_MPI_b    -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR3_MPI       -w work_PR3_MPI_c    -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR3_MPI       -w work_PR3_MPI_d    -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR3_MPI       -w work_PR3_MPI_a    -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR3_MPI       -w work_PR3_MPI_b    -m grdset_b          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR3_MPI       -w work_PR3_MPI_c    -m grdset_c          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR3_MPI       -w work_PR3_MPI_d    -m grdset_d          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR3_MPI       -w work_PR3_MPI_d2   -m grdset_d2         -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR3_MPI       -w work_PR3_MPI_e    -m grdset_e          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR3_MPI       -w work_PR3_MPI_b    -m grdset_b          -f -p $mpi -n $np $ww3 mww3_test_04
    $rtst -s PR3_MPI       -w work_PR3_MPI_c    -m grdset_c          -f -p $mpi -n $np $ww3 mww3_test_04
    $rtst -s PR3_MPI       -w work_PR3_MPI_d    -m grdset_d          -f -p $mpi -n $np $ww3 mww3_test_04
    $rtst -s PR3_MPI       -w work_PR3_MPI_e    -m grdset_e          -f -p $mpi -n $np $ww3 mww3_test_04

    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_a_c  -m grdset_a  -g curv -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_b_c  -m grdset_a  -g curv -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_c_c  -m grdset_a  -g curv -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_d_c  -m grdset_a  -g curv -f -p $mpi -n $np $ww3 mww3_test_02
    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_a_c  -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_b_c  -m grdset_b          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_c_c  -m grdset_c          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_d_c  -m grdset_d          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_d2_c -m grdset_d2         -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_e_c  -m grdset_e          -f -p $mpi -n $np $ww3 mww3_test_03
    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_b_c  -m grdset_b          -f -p $mpi -n $np $ww3 mww3_test_04
    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_c_c  -m grdset_c          -f -p $mpi -n $np $ww3 mww3_test_04
    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_d_c  -m grdset_d          -f -p $mpi -n $np $ww3 mww3_test_04
    $rtst -s PR3_MPI_SCRIP -w work_PR3_MPI_e_c  -m grdset_e          -f -p $mpi -n $np $ww3 mww3_test_04

    $rtst -s ST1_PR1_MPI   -w work_ST1_PR1_MPI  -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_05
    $rtst -s ST1_PR2_MPI   -w work_ST1_PR2_MPI  -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_05
    $rtst -s ST1_PR3_MPI   -w work_ST1_PR3_MPI  -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_05
    $rtst -s ST2_PR1_MPI   -w work_ST2_PR1_MPI  -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_05
    $rtst -s ST2_PR2_MPI   -w work_ST2_PR2_MPI  -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_05
    $rtst -s ST2_PR3_MPI   -w work_ST2_PR3_MPI  -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_05
    $rtst -s ST3_PR1_MPI   -w work_ST3_PR1_MPI  -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_05
    $rtst -s ST3_PR2_MPI   -w work_ST3_PR2_MPI  -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_05
    $rtst -s ST3_PR3_MPI   -w work_ST3_PR3_MPI  -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_05
    $rtst -s ST4_PR1_MPI   -w work_ST4_PR1_MPI  -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_05
    $rtst -s ST4_PR2_MPI   -w work_ST4_PR2_MPI  -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_05
    $rtst -s ST4_PR3_MPI   -w work_ST4_PR3_MPI  -m grdset_a          -f -p $mpi -n $np $ww3 mww3_test_05

# --------------------------------------------------------------------------- #
# Other / miscellaneous                                                       #
# --------------------------------------------------------------------------- #





# --------------------------------------------------------------------------- #
# Other .......... unknown or still to be done .........                      #
# --------------------------------------------------------------------------- #

#   $rtst $ww3 ww3_tp2.6
##  $rtst $ww3 ww3_tp2.7
##  $rtst $ww3 ww3_tp2.8
##  $rtst $ww3 ww3_tps4
##  $rtst $ww3 ww3_systrk_test_01
##  $rtst $ww3 mww3_test_06
##  $rtst $ww3 mww3_test_07
##  $rtst $ww3 arcticsub
##  $rtst $ww3 gbandd360

# --------------------------------------------------------------------------- #
# Default test setup, for testing of run_test only                            #
# --------------------------------------------------------------------------- #

  # $rtst                                              $ww3 ww3_tp1.1
  # $rtst                                              $ww3 ww3_tp1.2
  # $rtst                                              $ww3 ww3_tp1.3
  # $rtst                                              $ww3 ww3_tp1.4
  # $rtst                                              $ww3 ww3_tp1.5
  # $rtst                                              $ww3 ww3_tp1.6

  # $rtst                                              $ww3 ww3_tp2.1
  # $rtst                                              $ww3 ww3_tp2.2
  # $rtst                                              $ww3 ww3_tp2.3
  # $rtst                                              $ww3 ww3_tp2.4
  # $rtst                                              $ww3 ww3_tp2.5
 ## $rtst                                              $ww3 ww3_tp2.6
 ## $rtst                                              $ww3 ww3_tp2.7
 ## $rtst                                              $ww3 ww3_tp2.8

  # $rtst                                              $ww3 ww3_ts1
  # $rtst                                              $ww3 ww3_ts2
  # $rtst                                              $ww3 ww3_ts3

  # $rtst                                              $ww3 mww3_test_01
  # $rtst -m grdset_b                                  $ww3 mww3_test_02
  # $rtst -m grdset_d                                  $ww3 mww3_test_03
  # $rtst -m grdset_f                                  $ww3 mww3_test_04
  # $rtst -m grdset_a                -f -p $mpi -n $np $ww3 mww3_test_05
 ## $rtst                                              $ww3 mww3_test_06
 ## $rtst -m grdset                                    $ww3 mww3_test_07

# --------------------------------------------------------------------------- #
# End to the matrix                                                           #
# --------------------------------------------------------------------------- #
