#!/usr/bin/ksh
#
# @ error   = Error
# @ output  = Output
# @ output=S50WGrid.o$(jobid)
# @ error=S50WGrid.e$(jobid)
# @ notification  = never
# @ wall_clock_limit=1800
## @ job_type = parallel
## @ node = 1
# @ class = serial
## @ tasks_per_node = 1
# @ node_usage = shared
# @ resources = ConsumableCpus(1) ConsumableMemory(3600 mb)
# @ queue

##-----------------------------------------------------------------------------
#
# Description:  IBM Job script to run SMC50 ww3_grid 
# 
# First Created:    Jian-Guo Li   21 Jan 2009
# Last modified:    Jian-Guo Li   19 Nov 2013
#------------------------------------------------------------------------------

# Set up directory path:
RUNDIR='/home/nwp/ofrd/frjl/WW3Runs'
WW3DIR='/data/nwp/ofrd/frjl/WW3Vn4'
SCRDIR="/scratch/frjl_ww3"

# set mandatory WW3 environment variables:
export WW3_STRT_INP=ww3_strt
export WW3_SHEL_INP=ww3_shel
export WW3_GRID_INP=ww3_grid
export WW3_MOD_DEF=mod_def
export WW3_WIND=wind
export WW3_RESTART=restart
export WW3_LOG=log
export WW3_OUT_GRD=out_grd
export WW3_OUT_PNT=out_pnt

# Change to scratch directory for this run:
cd $SCRDIR
CC=$?
if test $CC -ne 0
then
 mkdir $SCRDIR
 cd    $SCRDIR
fi

echo "Clearing working dir `pwd`"
rm -f $SCRDIR/*

##############################################################################
## Copy executable and input files to scratch dir
## Note lat-lon grid model input files are still read by ww3_grid
##      though they are not used in the SMC version.  JGLi06Dec2010.
echo "Copy executables and input files ..."
cp $WW3DIR/exesmc/ww3_grid         ./
cp $WW3DIR/inps50/ww3_grid.inp     ./
cp $WW3DIR/inps50/G50SMCels.dat    ./
cp $WW3DIR/inps50/G50GISide.dat    ./
cp $WW3DIR/inps50/G50GJSide.dat    ./
cp $WW3DIR/inps50/G50SMCDepth.dat  ./
cp $WW3DIR/inps50/G50SMCMasks.dat  ./
cp $WW3DIR/inps50/G50SMCSubtr.dat  ./

ls -l

##############################################################################
##  Run the grid preprocessor:
banner Grid
   ./ww3_grid 

##  Save model definition file
cp mod_def.ww3  $WW3DIR/inps50/

banner End 

exit 0

