 emacs --batch -l .emacsloc yowdatapool.F90 -f mark-whole-buffer -f f90-indent-subprogram -f save-buffer
 emacs --batch -l .emacsloc yowelementpool.F90 -f mark-whole-buffer -f f90-indent-subprogram -f save-buffer
 emacs --batch -l .emacsloc yowerr.F90 -f mark-whole-buffer -f f90-indent-subprogram -f save-buffer
 emacs --batch -l .emacsloc yowexchangeModule.F90 -f mark-whole-buffer -f f90-indent-subprogram -f save-buffer
 emacs --batch -l .emacsloc yowfunction.F90 -f mark-whole-buffer -f f90-indent-subprogram -f save-buffer
 emacs --batch -l .emacsloc yownodepool.F90 -f mark-whole-buffer -f f90-indent-subprogram -f save-buffer
 emacs --batch -l .emacsloc yowpd.F90 -f mark-whole-buffer -f f90-indent-subprogram -f save-buffer
 emacs --batch -l .emacsloc yowpdlibmain.F90 -f mark-whole-buffer -f f90-indent-subprogram -f save-buffer
 emacs --batch -l .emacsloc yowrankModule.F90 -f mark-whole-buffer -f f90-indent-subprogram -f save-buffer
 emacs --batch -l .emacsloc yowsidepool.F90 -f mark-whole-buffer -f f90-indent-subprogram -f save-buffer
