#!/bin/bash
#
#PBS -N SubGtLksGrid 
#PBS -q shared
#PBS -l select=1:ncpus=1:mem=1GB
#PBS -l walltime=00:06:00
#PBS -j oe

# #PBS -q parallel
# #PBS -l select=1:ncpus=32

##-----------------------------------------------------------------------------
#
# Description:  Cray XC40 Job script to run ww3_grid 
# 
# First Created:    Jian-Guo Li   15 Jun 2015
# Last modified:    Jian-Guo Li   11 May 2021
#------------------------------------------------------------------------------

# Set up directory path:
RUNDIR='/home/d02/frjl/WW3Run'
WW3DIR='/data/d02/frjl/WW3Vn7'
INPDIR='/data/d02/frjl/WW3Vn7/inp'
SCRDIR="/scratch/d02/frjl/tstmlt"

# set mandatory WW3 environment variables:
export WW3_STRT_INP=ww3_strt
export WW3_SHEL_INP=ww3_shel
export WW3_GRID_INP=ww3_grid
export WW3_MOD_DEF=mod_def
export WW3_WIND=wind
export WW3_RESTART=restart
export WW3_LOG=log
export WW3_OUT_GRD=out_grd
export WW3_OUT_PNT=out_pnt

###### CrayPat related modules and file directory ######
# module load perftools-lite
# export CRAYPAT_LITE=sample_profile

# Change to scratch directory for this run:
cd $SCRDIR
CC=$?
if test $CC -ne 0
then
 mkdir $SCRDIR
 cd    $SCRDIR
fi

echo "Clearing working dir `pwd`"
rm -f $SCRDIR/*

##############################################################################
## Copy executable and input files to scratch dir
## Note lat-lon grid g25 model input files are still read by ww3_grid
##      though they are not used in the SMC version.  JGLi06Dec2010.
## New cell, face, depth, mask and sub-transparency files.  JGLi10Jan2012
echo "Copy executables and input files ..."
cp $WW3DIR/exemlt/ww3_grid          ./

## Loop over 3 sub-grids and run for ww3_grid.
for grd in Michi Huron Super 
do

  cp $INPDIR/ww3_grid_${grd}.inp ./ww3_grid.inp 
  cp $INPDIR/GtLk${grd}Cels.dat ./
  cp $INPDIR/GtLk${grd}ISid.dat ./
  cp $INPDIR/GtLk${grd}JSid.dat ./
  cp $INPDIR/GtLk${grd}Obst.dat ./
  cp $INPDIR/GtLk${grd}Blst.dat ./
  ls -l

##############################################################################
##  Run the grid preprocessor:
  echo " *** Grid $grd *** "
  ./ww3_grid 

##  Save model definition file
  cp mod_def.ww3  $INPDIR/mod_def.${grd}

  echo " *** End $grd *** "

done
## End of loop over 4 sub-grids.

exit 0
 
